- docs/_includes/join-us.html
Update text and add GH link, rename file to Join Us.
> Update, rename, add link to GH repo

- docs/_config.yml
Update _config.yml GH Pages Landing page title/tagline.
> Update landing page title-tagline

- CONTRIBUTING.md
Update Contributing to reflect Discussions page for community conversations, issues, etc.
> Update Contributing page

- docs/_config.yml
Updating header links on landing page
> Update _config.yml header links

- .github/workflows/ci.yml
Fixes wrong condition introduced by #69.
> Fix publishing unit tests in fork PRs

- alerting/alerting-core/pom.xml
- alerting/alerting-spark/pom.xml
- alerting/alerting-storm/pom.xml
- alerting/pom.xml
- config-editor/config-editor-core/pom.xml
- config-editor/config-editor-rest/pom.xml
- config-editor/config-editor-services/pom.xml
- config-editor/config-editor-sync/pom.xml
- config-editor/pom.xml
- deployment/storm-topology-manager/pom.xml
- enriching/enriching-core/pom.xml
- enriching/enriching-storm/pom.xml
- enriching/pom.xml
- parsing/parsing-app/pom.xml
- parsing/parsing-core/pom.xml
- parsing/parsing-storm/pom.xml
- parsing/pom.xml
- pom.xml
- responding/pom.xml
- responding/responding-core/pom.xml
- responding/responding-core/src/main/java/uk/co/gresearch/siembol/response/common/RespondingResultAttributes.java
- responding/responding-core/src/main/java/uk/co/gresearch/siembol/response/engine/ResponseRule.java
- responding/responding-stream/pom.xml
- responding/responding-stream/src/main/java/uk/co/gresearch/siembol/response/stream/ruleservice/KafkaStreamRulesService.java
- responding/responding-stream/src/main/java/uk/co/gresearch/siembol/response/stream/ruleservice/KafkaStreamsFactory.java
- responding/responding-stream/src/main/java/uk/co/gresearch/siembol/response/stream/ruleservice/KafkaStreamsFactoryImpl.java
- responding/responding-stream/src/test/java/uk/co/gresearch/siembol/response/stream/ruleservice/KafkaStreamRuleServiceTest.java
- responding/responding-stream/src/test/java/uk/co/gresearch/siembol/response/stream/ruleservice/TestingDriverKafkaStreamsFactory.java
- siembol-common/pom.xml
- siembol-common/src/main/java/uk/co/gresearch/siembol/common/error/ErrorMessage.java
improve reporting health in response stream
improve logging in response stream
refactoring unitests of kafka streams
> response: Improve kafka stream integration

- docs/_posts/2021-06-16-placeholder.md
- docs/_posts/2021-07-08-hat-conf.md
- docs/_posts/2021-07-09-def-conf.md
Added information about the two upcoming conferences (we don't have a photo, so using the template photo for now).
> added conferences to news page

- alerting/alerting-core/pom.xml
- alerting/alerting-spark/pom.xml
- alerting/alerting-storm/pom.xml
- alerting/pom.xml
- config-editor/config-editor-core/pom.xml
- config-editor/config-editor-rest/pom.xml
- config-editor/config-editor-services/pom.xml
- config-editor/config-editor-sync/pom.xml
- config-editor/config-editor-sync/src/main/java/uk/co/gresearch/siembol/configeditor/sync/actions/GetParsingAppStormTopologyAction.java
- config-editor/config-editor-sync/src/test/java/uk/co/gresearch/siembol/configeditor/sync/actions/GetParsingAppStormTopologyActionTest.java
- config-editor/pom.xml
- deployment/storm-topology-manager/pom.xml
- deployment/storm-topology-manager/src/main/java/uk/co/gresearch/siembol/deployment/storm/application/TopologyManagerConfiguration.java
- enriching/enriching-core/pom.xml
- enriching/enriching-storm/pom.xml
- enriching/pom.xml
- parsing/parsing-app/pom.xml
- parsing/parsing-core/pom.xml
- parsing/parsing-storm/pom.xml
- parsing/pom.xml
- pom.xml
- responding/pom.xml
- responding/responding-core/pom.xml
- responding/responding-stream/pom.xml
- siembol-common/pom.xml
> fixing null pointer exceptions in java applications

- docs/_posts/2021-08-19-bh-europe-conf
Adding 3rd news item to News section.
> Adding news item to News section

- README.md
Add badge for Black Hat Arsenal 2021
> add BH Arsenal 2021 badge

- .github/workflows/ci.yml
More info & comments you can find here https://github.com/G-Research/siembol/issues/135
> latest release and snapshot tags in docker images

- deployment/docker/storm-entrypoint.sh
Reverts G-Research/siembol#360
> Revert "deployment: Adding siembol user as an owner of a topology in docker image"

- deployment/docker/Dockerfile.storm
Reverts G-Research/siembol#363
> Revert "Update Dockerfile.storm"

- alerting/alerting-core/pom.xml
- alerting/alerting-spark/pom.xml
- alerting/alerting-storm/pom.xml
- alerting/pom.xml
- config-editor/config-editor-core/pom.xml
- config-editor/config-editor-rest/pom.xml
- config-editor/config-editor-services/pom.xml
- config-editor/config-editor-sync/pom.xml
- config-editor/config-editor-sync/src/main/java/uk/co/gresearch/siembol/configeditor/sync/service/EnrichmentTablesProviderImpl.java
- config-editor/pom.xml
- deployment/storm-topology-manager/pom.xml
- docs/introduction/how-tos/how_to_contribute.md
- enriching/enriching-core/pom.xml
- enriching/enriching-storm/pom.xml
- enriching/enriching-storm/src/main/java/uk/co/gresearch/siembol/enrichments/storm/MemoryTableEnrichmentBolt.java
- enriching/enriching-storm/src/test/java/uk/co/gresearch/siembol/enrichments/storm/MemoryTableEnrichmentBoltTest.java
- enriching/pom.xml
- parsing/parsing-app/pom.xml
- parsing/parsing-core/pom.xml
- parsing/parsing-storm/pom.xml
- parsing/pom.xml
- pom.xml
- responding/pom.xml
- responding/responding-core/pom.xml
- responding/responding-stream/pom.xml
- siembol-common/pom.xml
- siembol-common/src/main/java/uk/co/gresearch/siembol/common/testing/TestingZooKeeperConnectorFactory.java
Reworking updating tables in enrichment storm - tables are updated independently and only once per a path
Improving logging of updating table in config editor sync service
cleaning storm dependencies
> Improvements and fixes in enrichment tables 

- deployment/helm-k8s/resources/download.php
- deployment/helm-k8s/resources/index.php
- deployment/helm-k8s/resources/php.ini-local
- deployment/helm-k8s/resources/upload.php
- deployment/helm-k8s/templates/enrichment_store/configmap.yaml
- deployment/helm-k8s/templates/enrichment_store/deployment.yaml
- deployment/helm-k8s/templates/rest/deployment.yaml
- deployment/helm-k8s/templates/topology-manager/deployment.yaml
- deployment/helm-k8s/templates/topology-manager/serviceaccount-manager.yaml
- deployment/helm-k8s/values.yaml
- deployment/quickstart_install/ps-scripts/demoInstall.ps1
- deployment/quickstart_install/ps-scripts/dependencies.ps1
- deployment/quickstart_install/sh-scripts/demoInstall.sh
- deployment/quickstart_install/sh-scripts/dependencies.sh
PR includes:
**Enrichment:**
- Directory support
- Logging
- Filesize limit override (From 2MB to 10MB)
- Regex to validate directory path and filename
- HTTP response code
- index page 
POST request (directory path):
curl -F "uploaded_file=@FILENAME" -F "directory_path=/my_path" https://enrichment.local/upload.php
**Deployment:**
- removed one zk. Siembol and storm share same zk
- requesting less resources for config-editor-rest and storm-topology-manger
- added namespace field for storm-topology-manager
> Deployment: enrichment store, values, quickstart install

- deployment/helm-k8s/resources/upload.php
- deployment/quickstart_install/ps-scripts/demoInstall.ps1
- deployment/quickstart_install/sh-scripts/demoInstall.sh
- docs/deployment/how-tos/how_to_set_up_zookeeper_nodes.md
removing creating ZooKeeper nodes from quickstart install
adding underscore char into allowed upload name in enrichment store
> deployment: adding ZooKeeper autocreation documentation

- docs/_posts/2021-07-08-hat-conf.md
- docs/_posts/2021-08-19-bh-europe-conf.md
- docs/_posts/2021-11-10-ato-conf.md
This PR updates the links to the ATO and BHUS21 videos on Youtube and adds the video link for BHEU21
> Update YouTube links

- alerting/alerting-core/pom.xml
- alerting/alerting-spark/pom.xml
- alerting/alerting-storm/pom.xml
- alerting/pom.xml
- config-editor/config-editor-core/pom.xml
- config-editor/config-editor-core/src/main/java/uk/co/gresearch/siembol/configeditor/serviceaggregator/ServiceAggregator.java
- config-editor/config-editor-rest/pom.xml
- config-editor/config-editor-rest/src/main/java/uk/co/gresearch/siembol/configeditor/rest/SynchronisationServiceController.java
- config-editor/config-editor-services/pom.xml
- config-editor/config-editor-sync/pom.xml
- config-editor/config-editor-sync/src/main/java/uk/co/gresearch/siembol/configeditor/sync/service/StormApplicationProvider.java
- config-editor/config-editor-sync/src/main/java/uk/co/gresearch/siembol/configeditor/sync/service/StormApplicationProviderImpl.java
- config-editor/config-editor-sync/src/test/java/uk/co/gresearch/siembol/configeditor/sync/service/StormApplicationProviderTest.java
- config-editor/pom.xml
- deployment/storm-topology-manager/pom.xml
- enriching/enriching-core/pom.xml
- enriching/enriching-storm/pom.xml
- enriching/pom.xml
- parsing/parsing-app/pom.xml
- parsing/parsing-core/pom.xml
- parsing/parsing-storm/pom.xml
- parsing/pom.xml
- pom.xml
- responding/pom.xml
- responding/responding-core/pom.xml
- responding/responding-stream/pom.xml
- siembol-common/pom.xml
> Config editor rest: adding restart all apps

- alerting/alerting-core/pom.xml
- alerting/alerting-spark/pom.xml
- alerting/alerting-storm/pom.xml
- alerting/pom.xml
- config-editor/config-editor-core/pom.xml
- config-editor/config-editor-rest/pom.xml
- config-editor/config-editor-services/pom.xml
- config-editor/config-editor-sync/pom.xml
- config-editor/pom.xml
- deployment/siembol-monitoring/pom.xml
- deployment/storm-topology-manager/pom.xml
- docs/services/siembol_parsing_services.md
- enriching/enriching-core/pom.xml
- enriching/enriching-storm/pom.xml
- enriching/pom.xml
- parsing/parsing-app/pom.xml
- parsing/parsing-app/src/main/java/uk/co/gresearch/siembol/parsers/application/factory/ParsingApplicationFactoryAttributes.java
- parsing/parsing-app/src/main/java/uk/co/gresearch/siembol/parsers/application/factory/ParsingApplicationFactoryImpl.java
- parsing/parsing-app/src/main/java/uk/co/gresearch/siembol/parsers/application/model/ParsingApplicationSettingsDto.java
- parsing/parsing-app/src/test/java/uk/co/gresearch/siembol/parsers/application/factory/ParsingApplicationFactoryImplTest.java
- parsing/parsing-core/pom.xml
- parsing/parsing-storm/pom.xml
- parsing/parsing-storm/src/main/java/uk/co/gresearch/siembol/parsers/storm/StormParsingApplication.java
- parsing/parsing-storm/src/test/java/uk/co/gresearch/siembol/parsers/storm/StormParsingApplicationTest.java
- parsing/pom.xml
- pom.xml
- responding/pom.xml
- responding/responding-core/pom.xml
- responding/responding-stream/pom.xml
- siembol-common/pom.xml
fixes #531 
- overwrite storm "topology.workers" attributes from new "num_worker" setting of parsing application
- fixing header routing app with null headers
-#clo
> Parsing: simplifying parsing app settings

- README.md
This PR adds a formatted warning to indicate that the project is no longer maintained.
> [ARCHIVING] update README.md: add warning "no longer maintained"
